package com.ztm.common.model;

import com.jfinal.plugin.activerecord.Page;
import com.ztm.common.model.base.BaseZkPosts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZkPosts extends BaseZkPosts<ZkPosts> {
	public static final ZkPosts dao = new ZkPosts();

	/**
	 * 所有 sql 与业务逻辑写在 Model 或 Service 中，不要写在 Controller 中，养成好习惯，有利于大型项目的开发与维护
	 */
	public Page<ZkPosts> paginate(int pageNumber, int pageSize, boolean remen) {

		String add="";
		if(remen)
			add = " t where t.readNum>1000 ";



		return paginate(pageNumber, pageSize, "select *", "from zk_posts "+add+"order by id desc");
	}
}
